### ISSUE TITLE
`react-smooth-dnd` causing `Illegal Invocation` error

### ISSUE THREAD

**Issue by PatchesMaps** [MonsantoCo/ol-kit#138]
Given our history with `react-smooth-dnd` (frequent bugs, instability, etc.) we have decided that it would be prudent to remove the dependency entirely.

The found behavior is similar to that described in [these](https://github.com/kutlugsahin/smooth-dnd/issues/74) [issues](https://github.com/kutlugsahin/smooth-dnd/issues/36) except that 
```
Object.defineProperty(global, 'Node', {
  value: { firstElementChild: 'firstElementChild' }
})
```
does not seem to resolve the problem.

**Comment by stazrad** [comment]
💯
