### ISSUE TITLE
Fix snapshots to ignore styled-components classNames

### ISSUE THREAD

**Issue by stazrad** [MonsantoCo/ol-kit#19]
The snapshots will keep failing until we get `jest-styled-components` to work with the `@testing-library` outputs

**Comment by glenselle** [comment]
Or just drop snapshots altogether 🤷‍♂

**Comment by stazrad** [comment]
this actually a problem with using `prettyDOM` to wrap our components before the snapshots- drop this and `jest-styled-components` will take care of the classnames
