### ISSUE TITLE
<Map> needs to display without requiring fullScreen

### ISSUE THREAD

**Issue by stazrad** [MonsantoCo/ol-kit#196]
If there is no parent container or `fullScreen` flag is not passed, the map doesn't display (as of `1.0.0`?)

**Comment by stazrad** [comment]
@UsmanAhmadSaeed this would be a great one to pick up- there's something going on with the CSS...when you create a `<Map>` without passing `fullScreen=true` it should be defaulting to the width of your screen with a `relative` position (`fullScreen` sets it to a `fixed` position)...but it doesn't appear on the page at all, presumably a bug with the css.

**Comment by UsmanAhmadSaeed** [comment]
@stazrad thanks. Could you point me to resource files for this? and how to reproduce this issue?

**Comment by stazrad** [comment]
@UsmanAhmadSaeed:
1. `git pull origin master`
2. `npm i`
3. `npm run app`
4. open the app on `localhost:2020`
5. remove the `fullScreen` prop here and figure out why screen is blank white (inspect the Elements and you'll see a div with a map identifier under the `<div id="root">` tag even tho it is not visible on the page)
<img width="422" alt="Screen Shot 2020-10-09 at 12 32 40 PM" src="https://user-images.githubusercontent.com/17538943/95614065-92575300-0a2b-11eb-917e-2314a71d8133.png">

**Comment by UsmanAhmadSaeed** [comment]
@stazrad sure, I'll begin working right away.

**Comment by UsmanAhmadSaeed** [comment]
Hey @stazrad `npm run app`  fails with the following error. I've checked and dependencies are up to-date. Tried executing command in both bash shell and cmd for Windows.

> @bayer/ol-kit@1.0.2 app C:\Users\usman\desktop\ol-kit
> OL_KIT_DEVELOPMENT=true webpack-dev-server --hot --inline --config app/webpack.config.js

'OL_KIT_DEVELOPMENT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bayer/ol-kit@1.0.2 app: `OL_KIT_DEVELOPMENT=true webpack-dev-server --hot --inline --config app/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bayer/ol-kit@1.0.2 app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
....

**Comment by stazrad** [comment]
ooh bizarre- we've only done dev work on macs 🤔  you can remove `OL_KIT_DEVELOPMENT=true` but you'll need to go replace `process.env.OL_KIT_DEVELOPMENT` with `true` (to force the alias) [on this line here](https://github.com/MonsantoCo/ol-kit/blob/5bd504f938cb199496668f7803c04fa93ac613c3/app/webpack.config.js#L7) @UsmanAhmadSaeed

**Comment by stazrad** [comment]
@UsmanAhmadSaeed alternatively- you could tackle the new issue i just created to set these env variables on pc/mac: https://github.com/MonsantoCo/ol-kit/issues/221 👍

**Comment by UsmanAhmadSaeed** [comment]
@stazrad Sure, I'd be happy to that on, but first I'll try this one.

**Comment by UsmanAhmadSaeed** [comment]
@stazrad It's the position being set to relative by styled.js in absence of fullScreen prop, and replacing the condition with just the "fixed" value for position resolves the issue. I don't why was it conditional, and as per my test and run, nothing breaks after changes.
I'll try to make only one PR with the env issue resolved too, hopefully, along with this.
Should I run `npm run build` after the changes, and before committing, to include new build in PR?

**Comment by UsmanAhmadSaeed** [comment]
@stazrad Both issues resolved. Just need to know:
* Should I resolve #221 in app folder as well, where package.json takes `NODE_ENV=development` in app script. (I guess that too, might cause an error in windows)?
* Should I run `npm run build` before opening the PR, to include new build in PR?

**Comment by UsmanAhmadSaeed** [comment]
Alright, I won't be available or active for a few days, so I'm opening PR with both issues resolved and without executing any build commands/scripts.
