### ISSUE TITLE
Map components hang indefinitely when async onMapInit has failure

### ISSUE THREAD

**Issue by ntatko** [MonsantoCo/ol-kit#201]
In the example right now, the request to get data fails, which causes the child components to never mount. I propose two solutions: 

1.) have IAs add try/catches to their own `onMapInit`'s 
2.) wrap `Map`'s `onMapInit` inside of a try catch

I don't care, I will let the community decide.

**Comment by stazrad** [comment]
This PR #205 would address this issue and add some resilience on our internal promise chain for the `onMapInit` block... @ntatko/community 👀
