### ISSUE TITLE
Create map-from-scratch cli

### ISSUE THREAD

**Issue by AtherBilal** [MonsantoCo/ol-kit#204]
1. git clone ol-kit
1. cd into app, delete everything else
1. init `package.json`
1. use `depcheck` to update `package.json` dependencies
1. install those dependencies with --save
1. *BOOM* you got a map app from scratch

Directory breakdown:
will live in `~/cli`
run `npm publish` from `cli` dir to ship to npm
add `package.json` script to publish cli

**Comment by stazrad** [comment]
solved by #220
