### ISSUE TITLE
Update docs for OL6

### ISSUE THREAD

**Issue by PizzaBrandon** [MonsantoCo/ol-kit#207]

**Comment by UsmanAhmadSaeed** [comment]
Hey,
I am a beginner in React.js, Can I be of help in updating docs?
Could you please provide some details of the task?
I'm looking to contribute as part of hacktoberfest.
Looking forward to hearing back
Thanks.

**Comment by stazrad** [comment]
@UsmanAhmadSaeed yes! & it will give you major contribution points 📈 
1. fork the repo
2. replace `ol@4.6.5` with just `ol` on this line: https://github.com/MonsantoCo/ol-kit/blob/master/src-docs/overrides/index.html#L76
3. the `render` function in the "Getting Started" example is empty for some reason (see here: https://ol-kit.com/), this needs to match the `README` in this repo
4. `npm run docs` to build the docs site locally & check they look good by opening `~/docs/index.html` in your browser
5. open a PR into `master` & you've contributed major lines! 🎉 

Just comment in this thread if you run into any snags 😉

**Comment by UsmanAhmadSaeed** [comment]
Hey @stazrad , for some reason, `npm run docs` doesn't work on my local clone. I've installed dependencies, but it returns an error. Anyways, I've updated the code and replaced the said name, and am pretty sure it will work.
Opened and checked https://github.com/MonsantoCo/ol-kit/blob/master/src-docs/overrides/index.html in browser, and it displays the render function correctly.
Making a PR.
Let me know if there's anything else I can do.

**Comment by stazrad** [comment]
Nice work! @UsmanAhmadSaeed i just merged a fix that should let you build docs- `git pull origin master` and you should be updated

**Comment by UsmanAhmadSaeed** [comment]
@stazrad ah alright, so should I make a new PR after `npm run docs`?

**Comment by stazrad** [comment]
@UsmanAhmadSaeed nope same PR just a new commit & push up the doc output

**Comment by UsmanAhmadSaeed** [comment]
@stazrad It's done.
Thanks!
