### ISSUE TITLE
More robust multi-map context support

### ISSUE THREAD

**Issue by glenselle** [MonsantoCo/ol-kit#63]
https://github.com/MonsantoCo/ol-kit/blob/3c767af214197c1c5a3362f7d7d0a7f2f80610c0/src/Map/Map.js#L13

Our current design is not very well suited to multi-map support which will probably make its way from internal source to ol-kit. We generally had trouble solving this since we didn't have a central store of any kind. One solution would be to use `localStorage` APIs. We could add a prop so people could disable this if they would rather not haver ol-kit "polluting" `localStorage`, however it's fairly reasonable to assume most implementors will have a store of their own and thus wouldn't use `localStorage` for much if anything.

**Comment by stazrad** [comment]
We do need a more robust way to handle multimaps but why `localStorage`? that would make sense if we were trying to persist data between sessions or something but we can just use a HOC `<MultiMapManager>` or something handles "storage" for the length of the session.

**Comment by glenselle** [comment]
True, an HOC could work in some cases. Only bummer is that you're creating these overarching comps which can never be unmounted.

**Comment by PizzaBrandon** [comment]
Covered by #192
