### ISSUE TITLE
Compile list of open and interesting datasets

### ISSUE THREAD

**Issue by PizzaBrandon** [MonsantoCo/ol-kit#80]
- Get good links from the following sources
  - Data.gov
  - Census data
  - Arcgis (with help on how to use it)
  - Others
- Add to docs

**Comment by UsmanAhmadSaeed** [comment]
Hey, is it still up for grabs?
If yes, kindly provide some info as on where to put datasets in docs and I'll take it.

**Comment by AtherBilal** [comment]
Yes, this is totally up for grabs. I would say put it under tutorials, titled `Working with Datasets`. If you want to see examples of datasets being used, checkout our demo site at https://demo.ol-kit.com/
![image](https://user-images.githubusercontent.com/19599476/95487562-1a6d2800-095a-11eb-9d7e-7d2ec67b47d0.png)

**Comment by UsmanAhmadSaeed** [comment]
@AtherBilal This will only be a list of resources with brief descriptions, right?
What kind of datasets and resources should I add? Are there any requirements, or simply link to any geographic related dataset with brief description should work?
And could you please point me to the correct file, that generates the documentation page?
Please excuse me too, for I'm just a beginner.

**Comment by AtherBilal** [comment]
We would like to add not only links to datasets but also a short tutorial on how to use them. We have an example that you can take a look right over [`Here`](https://github.com/MonsantoCo/ol-kit/blob/master/app/demos/covid/DataLoader.js#L16)

You can add a markdown `DataSets.md` file in this [directory](https://github.com/MonsantoCo/ol-kit/tree/master/src-docs/tutorials).

**Comment by ntatko** [comment]
I happen to have put together a bunch of cool(ish) data sets that are open to the public. What if I would expose them as, I dunno, an exportable set? I'll see if I can get a PR that does something like this.
